services:
  linkding:
    image: sissbruecker/linkding:1.45.0
    container_name: linkding
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - linkding_data:/etc/linkding/data
    env_file:
      - .env

volumes:
  linkding_data: